# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/elfin',
                'doc_host': 'https://DAMI-research.github.io',
                'git_url': 'https://github.com/DAMI-research/elfin',
                'lib_path': 'elfin'},
  'syms': {'elfin.core': {'elfin.core.foo': ('core.html#foo', 'elfin/core.py')}}}
