# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/elfin',
                'doc_host': 'https://DAMI-research.github.io',
                'git_url': 'https://github.com/DAMI-research/elfin',
                'lib_path': 'elfin'},
  'syms': { 'elfin.core': { 'elfin.core.denoise': ('core.html#denoise', 'elfin/core.py'),
                            'elfin.core.motion_correction': ('core.html#motion_correction', 'elfin/core.py')}}}
