# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto 0
__all__ = ['denoise', 'motion_correction']

# %% ../nbs/core.ipynb 3
def denoise(a=1, b=2): 
    return a+b 

# %% ../nbs/core.ipynb 4
def motion_correction(to): 
    "say hello to somebody"
    return f'Hello {to}!'
